export const ErrorCode = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNSUPPORTED_SOURCE: 'UNSUPPORTED_SOURCE',
  TARGET_RATE_LIMITED: 'TARGET_RATE_LIMITED',
  TARGET_BLOCKED: 'TARGET_BLOCKED',
  TARGET_TIMEOUT: 'TARGET_TIMEOUT',
  PARTIAL_RESPONSE: 'PARTIAL_RESPONSE',
  EMPTY_RESPONSE: 'EMPTY_RESPONSE',
  PARSING_FAILED: 'PARSING_FAILED',
  TARGET_UNAVAILABLE: 'TARGET_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
